export const types = {
    // Sync
    FILL_TODOS:       "FILL_TODOS",
    CREATE_TODO:      "CREATE_TODO",
    REMOVE_TODO:      "REMOVE_TODO",
    FAVOURITE_TODO:   "FAVOURITE_TODO",
    UNFAVOURITE_TODO: "UNFAVOURITE_TODO",
    COMPLETE_TODO:    "COMPLETE_TODO",
    UNCOMPLETE_TODO:  "UNCOMPLETE_TODO",

    // Async
    FETCH_TODOS_ASYNC:      "FETCH_TODOS_ASYNC",
    CREATE_TODO_ASYNC:      "FETCH_TODO_ASYNC",
    REMOVE_TODO_ASYNC:      "REMOVE_TODO_ASYNC",
    FAVOURITE_TODO_ASYNC:   "FAVOURITE_TODO_ASYNC",
    UNFAVOURITE_TODO_ASYNC: "UNFAVOURITE_TODO_ASYNC",
    COMPLETE_TODO_ASYNC:    "COMPLETE_TODO_ASYNC",
    UNCOMPLETE_TODO_ASYNC:  "UNCOMPLETE_TODO_ASYNC",
};
