export const types = {
    // Sync
    FILL_TASKS:      "FILL_TASKS",
    CREATE_TASK:     "CREATE_TASK",
    REMOVE_TASK:     "REMOVE_TASK",
    FAVORITE_TASK:   "FAVORITE_TASK",
    UNFAVORITE_TASK: "UNFAVORITE_TASK",
    COMPLETE_TASK:   "COMPLETE_TASK",
    UNCOMPLETE_TASK: "UNCOMPLETE_TASK",

    // Async
    FETCH_TASKS_ASYNC:     "FETCH_TASKS_ASYNC",
    CREATE_TASK_ASYNC:     "FETCH_TASK_ASYNC",
    REMOVE_TASK_ASYNC:     "REMOVE_TASK_ASYNC",
    FAVORITE_TASK_ASYNC:   "FAVORITE_TASK_ASYNC",
    UNFAVORITE_TASK_ASYNC: "UNFAVORITE_TASK_ASYNC",
    COMPLETE_TASK_ASYNC:   "COMPLETE_TASK_ASYNC",
    UNCOMPLETE_TASK_ASYNC: "UNCOMPLETE_TASK_ASYNC",
};
