export const types = {
    // Sync
    FILL_TASKS:           "FILL_TASKS",
    CREATE_TASK:          "CREATE_TASK",
    UPDATE_TASK:          "UPDATE_TASK",
    REMOVE_TASK:          "REMOVE_TASK",
    TOGGLE_FAVORITE_TASK: "TOGGLE_FAVORITE_TASK",
    TOGGLE_COMPLETE_TASK: "TOGGLE_COMPLETE_TASK",
    TOGGLE_FOCUS_TASK:    "TOGGLE_FOCUS_TASK",
    SORT_TASKS:           "SORT_TASKS",
    SEARCH_TASKS:         "SEARCH_TASKS",

    // Async
    FETCH_TASKS_ASYNC:          "FETCH_TASKS_ASYNC",
    CREATE_TASK_ASYNC:          "FETCH_TASK_ASYNC",
    UPDATE_TASK_ASYNC:          "UPDATE_TASK_ASYNC",
    REMOVE_TASK_ASYNC:          "REMOVE_TASK_ASYNC",
    TOGGLE_FAVORITE_TASK_ASYNC: "TOGGLE_FAVORITE_TASK_ASYNC",
    TOGGLE_COMPLETE_TASK_ASYNC: "TOGGLE_COMPLETE_TASK_ASYNC",
};
